name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Lint and test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make test
